joint_config = {
    "data_dir" : './data',
    #"train_file" : 'train.json',
    "train_file" : 'smp_train_ehance.json',
    #"train_file" : 'smp_2019_task1_train.json',
    "bert_config_file" : './chinese_L-12_H-768_A-12/bert_config.json',
    "task_name" : 'joint',
    "vocab_file" : 'chinese_L-12_H-768_A-12/vocab.txt',
    "output_dir" : 'output/',
    "init_checkpoint" : './chinese_L-12_H-768_A-12/bert_model.ckpt',
    "do_lower_case" : True,
    "max_seq_length" : 128,
    "do_train" : False,
    "do_eval" : False,
    "do_predict" : True,
    "do_serve" : False,
    "train_batch_size" : 16,
    "eval_batch_size" : 32,
    "predict_batch_size" : 16,
    "learning_rate" : 5e-5,
    "num_train_epochs" : 40.0,
    "warmup_proportion" : 0.1,
    "save_checkpoints_steps": 1000,
    "iterations_per_loop" : 1000,
    "use_tpu" : False,
    "tpu_name" : None,
    "tpu_zone" : None,
    "gcp_project" : None,
    "master" : None,
    "num_tpu_cores" : 8,
    "label_file" : 'labels_map',
    "export_dir" : None,
    "lstm_size" : 100,
    "cell" : "lstm",
    "num_layers" : 1,
    "dropout_rate" : 0.5,
}

